language: java
jdk: oraclejdk8
install: true
sudo: false
branches:
  except:
    - legacy
    - experimental

cache:
  directories:
    - '$HOME/.sonar/cache'
    
env:
  global:
    - SONAR_TOKEN: d043ef3ea7d081203e4eca0ac14b14d0054b6c43
    - SONAR_HOST_URL: https://sonarqube.com
before_install:
 - export TZ=America/New_York	
